from enum import StrEnum


class SimulationScenario(StrEnum):
    NORMAL = "NORMAL"
    CARD_TESTING = "CARD_TESTING"
    HIGH_VELOCITY = "HIGH_VELOCITY"
    ACCOUNT_TAKEOVER = "ACCOUNT_TAKEOVER"
    IMPOSSIBLE_TRAVEL = "IMPOSSIBLE_TRAVEL"
    NEW_DEVICE_HIGH_VALUE = "NEW_DEVICE_HIGH_VALUE"
    SHARED_DEVICE_FRAUD = "SHARED_DEVICE_FRAUD"
    FRAUD_RING = "FRAUD_RING"
